server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-driver-user?characterEncoding=utf-8&serverTimeZone=GMT%2B8
    username: root
    password: root
  application:
    name: service-driver-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  level:
    com.baomidou.mybatisplus: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  service:
    vgroup-mapping.my_tx: seata-tc
    grouplist.seata-tc: 127.0.0.1:8101;127.0.0.1:8102;127.0.0.1:8103
  tx-service-group: my_tx