server:
  port: 8089

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-order?characterEncoding=utf-8&serverTimeZone=GMT%2B8
    username: root
    password: root
  application:
    name: service-order
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

logging:
  level:
    com.baomidou: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

zookeeper:
  address: localhost:2181,localhost:2182,localhost:2183
  timeout: 100000

seata:
  service:
    vgroup-mapping.my_tx: seata-tc
    grouplist.seata-tc: 127.0.0.1:8101;127.0.0.1:8102;127.0.0.1:8103
  tx-service-group: my_tx

---
spring:
  profiles: 8090
server:
  port: 8090

---
spring:
  profiles: 8091
server:
  port: 8091